# **Pandas**

How to import data and work with data using pandas

In [21]:
import  pandas as pd

We should mount google drive beforeuse. If we don't mount our google drive error will show.

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [23]:
url = '/content/drive/My Drive/Data_for_ML/cars_info.csv'
df = pd.read_csv(url)

In [24]:
df.head()

,ID,Name,Price,Brand,Model,Variant,Series,Year,Kilometers,Type,Gearbox,Fuel,Status,CC,Color,Seating Capacity
0,11530130,2010 Toyota Rukus Build 2 AZE151R,9999,Toyota,Rukus,Build 2,AZE151R,2010,263000,Wagon,Automatic,Unleaded Petrol,Used,2362,Grey,5
1,12190570,2021 Mercedes-Benz V 250 D Avantgarde MWB 447 ...,117990,Mercedes-Benz,V,250 D Avantgarde MWB,447 MY21,2021,19,Wagon,Automatic,Diesel,New In Stock,2143,Black,7
2,12321855,2021 Mercedes-Benz Valente 116 CDI MWB RWD 447...,79990,Mercedes-Benz,Valente,116 CDI MWB RWD,447 MY21,2021,24,Wagon,Automatic,Diesel,New In Stock,2143,Black,8
3,12346971,2010 Mercedes-Benz E250 CDI Avantgarde 207,34990,Mercedes-Benz,E250,CDI Avantgarde,207,2010,120579,Cabriolet,Automatic,Diesel,Used,2143,Black,4
4,12363884,2016 Holden Cruze CD JH MY16,15990,Holden,Cruze,CD,JH MY16,2016,72506,Sportswagon,Automatic,Unleaded Petrol,Used,1796,White,5

If we use header = None it will treat first raw also as a dataset ( features)

In [25]:
df1 = pd.read_csv(url, header = None)
df1.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,ID,Name,Price,Brand,Model,Variant,Series,Year,Kilometers,Type,Gearbox,Fuel,Status,CC,Color,Seating Capacity
1,11530130,2010 Toyota Rukus Build 2 AZE151R,9999,Toyota,Rukus,Build 2,AZE151R,2010,263000,Wagon,Automatic,Unleaded Petrol,Used,2362,Grey,5
2,12190570,2021 Mercedes-Benz V 250 D Avantgarde MWB 447 ...,117990,Mercedes-Benz,V,250 D Avantgarde MWB,447 MY21,2021,19,Wagon,Automatic,Diesel,New In Stock,2143,Black,7
3,12321855,2021 Mercedes-Benz Valente 116 CDI MWB RWD 447...,79990,Mercedes-Benz,Valente,116 CDI MWB RWD,447 MY21,2021,24,Wagon,Automatic,Diesel,New In Stock,2143,Black,8
4,12346971,2010 Mercedes-Benz E250 CDI Avantgarde 207,34990,Mercedes-Benz,E250,CDI Avantgarde,207,2010,120579,Cabriolet,Automatic,Diesel,Used,2143,Black,4

Read data in the bottom.

In [26]:
df2 = df.tail()
df2.head()

,ID,Name,Price,Brand,Model,Variant,Series,Year,Kilometers,Type,Gearbox,Fuel,Status,CC,Color,Seating Capacity
17043,12852453,2003 Holden Commodore Executive VY,4499,Holden,Commodore,Executive,VY,2003,230441,Sedan,Automatic,Unleaded Petrol,Used,3791,Gold,5
17044,12852460,2008 Toyota Yaris YR NCP90R,4999,Toyota,Yaris,YR,NCP90R,2008,237113,Hatchback,Manual,Unleaded Petrol,Used,1299,Yellow,5
17045,12852462,2002 Holden Jackaroo SE LWB (4X4) U8,7999,Holden,Jackaroo,SE LWB (4X4),U8,2002,238768,Wagon,Automatic,Diesel,Used,2999,Gold,7
17046,12852463,2016 Hyundai I30 Active GD4 Series 2,14000,Hyundai,I30,Active,GD4 Series 2,2016,49800,Hatchback,Manual,Unleaded Petrol,Used,1797,Blue,5
17047,12852464,2005 Toyota RAV4 Cruiser (4X4) ACA23R,5999,Toyota,RAV4,Cruiser (4X4),ACA23R,2005,255809,Wagon,Manual,Unleaded Petrol,Used,2362,Grey,5

Change the column names of the data frame

In [27]:
df.columns

Index(['ID', 'Name', 'Price', 'Brand', 'Model', 'Variant', 'Series', 'Year',
       'Kilometers', 'Type', 'Gearbox', 'Fuel', 'Status', 'CC', 'Color',
       'Seating Capacity'],
      dtype='object')

In [29]:
df.columns = ['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
       'Acceleration', 'Model', 'Origin', 'Car Name', 'Year', 'Price', 'Type', 'DriveTrain', 'name', 'mode']

In [30]:
df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,Car Name,Year,Price,Type,DriveTrain,name,mode
0,11530130,2010 Toyota Rukus Build 2 AZE151R,9999,Toyota,Rukus,Build 2,AZE151R,2010,263000,Wagon,Automatic,Unleaded Petrol,Used,2362,Grey,5
1,12190570,2021 Mercedes-Benz V 250 D Avantgarde MWB 447 ...,117990,Mercedes-Benz,V,250 D Avantgarde MWB,447 MY21,2021,19,Wagon,Automatic,Diesel,New In Stock,2143,Black,7
2,12321855,2021 Mercedes-Benz Valente 116 CDI MWB RWD 447...,79990,Mercedes-Benz,Valente,116 CDI MWB RWD,447 MY21,2021,24,Wagon,Automatic,Diesel,New In Stock,2143,Black,8
3,12346971,2010 Mercedes-Benz E250 CDI Avantgarde 207,34990,Mercedes-Benz,E250,CDI Avantgarde,207,2010,120579,Cabriolet,Automatic,Diesel,Used,2143,Black,4
4,12363884,2016 Holden Cruze CD JH MY16,15990,Holden,Cruze,CD,JH MY16,2016,72506,Sportswagon,Automatic,Unleaded Petrol,Used,1796,White,5

In [32]:
url = '/content/drive/My Drive/Data_for_ML/cars_info.csv'
df_new = pd.read_csv(url)
df_new.head(1)

,ID,Name,Price,Brand,Model,Variant,Series,Year,Kilometers,Type,Gearbox,Fuel,Status,CC,Color,Seating Capacity
0,11530130,2010 Toyota Rukus Build 2 AZE151R,9999,Toyota,Rukus,Build 2,AZE151R,2010,263000,Wagon,Automatic,Unleaded Petrol,Used,2362,Grey,5

Save the file in a specific path

In [33]:
path = '/content/drive/My Drive/Data_for_ML/cars_info_new.csv'
df_new.to_csv(path)

In [44]:
df.to_csv("automobile.csv", index=False)
# Here use index = False when index is not need

It is very important to check whether all data are in correct form. If there is any mismatch data in data frame we can identify that error using this method

In [34]:
df_new.dtypes

ID                   int64
Name                object
Price                int64
Brand               object
Model               object
Variant             object
Series              object
Year                 int64
Kilometers           int64
Type                object
Gearbox             object
Fuel                object
Status              object
CC                   int64
Color               object
Seating Capacity     int64
dtype: object

By using  describe function we can see the statistical summary.With the help of his summary we can see the deviations which may occur in datasets.

In [39]:
df_new.describe()

,ID,Price,Year,Kilometers,CC,Seating Capacity
count,1.704800e+04,17048.000000,17048.000000,1.704800e+04,17048.000000,17048.000000
mean,1.279027e+07,36777.778038,2015.481288,1.032314e+05,2491.830303,5.115849
std,5.051111e+04,30305.015328,4.721591,8.041313e+04,881.985562,1.121791
min,1.153013e+07,1000.000000,1989.000000,1.000000e+00,875.000000,2.000000
25%,1.275715e+07,18800.000000,2013.000000,4.450225e+04,1987.000000,5.000000
50%,1.280207e+07,29990.000000,2016.000000,8.845400e+04,2354.000000,5.000000
75%,1.283131e+07,45990.000000,2019.000000,1.488735e+05,2981.000000,5.000000
max,1.285246e+07,999000.000000,2022.000000,2.700000e+06,7300.000000,14.000000

To get full data summary. we can use all method inside the describe.Here unique is the number of distinct objects in columns. Top is most frequently occuring object. Freq is number of time top object occur.We an see NaN becuase these columns contains non-Numerical values.

In [40]:
df_new.describe(include = 'all')

,ID,Name,Price,Brand,Model,Variant,Series,Year,Kilometers,Type,Gearbox,Fuel,Status,CC,Color,Seating Capacity
count,1.704800e+04,17048,17048.000000,17048,17048,17048,17048,17048.000000,1.704800e+04,17048,17048,17048,17048,17048.000000,17048,17048.000000
unique,NaN,8575,NaN,59,622,2363,2286,NaN,NaN,56,5,7,3,NaN,235,NaN
top,NaN,2018 Nissan X-Trail ST (2WD) T32 Series 2,NaN,Toyota,Ranger,S,MY18,NaN,NaN,Wagon,Automatic,Unleaded Petrol,Used,NaN,White,NaN
freq,NaN,33,NaN,2768,648,287,172,NaN,NaN,7768,14578,7016,16304,NaN,6177,NaN
mean,1.279027e+07,NaN,36777.778038,NaN,NaN,NaN,NaN,2015.481288,1.032314e+05,NaN,NaN,NaN,NaN,2491.830303,NaN,5.115849
std,5.051111e+04,NaN,30305.015328,NaN,NaN,NaN,NaN,4.721591,8.041313e+04,NaN,NaN,NaN,NaN,881.985562,NaN,1.121791
min,1.153013e+07,NaN,1000.000000,NaN,NaN,NaN,NaN,1989.000000,1.000000e+00,NaN,NaN,NaN,NaN,875.000000,NaN,2.000000
25%,1.275715e+07,NaN,18800.000000,NaN,NaN,NaN,NaN,2013.000000,4.450225e+04,NaN,NaN,NaN,NaN,1987.000000,NaN,5.000000
50%,1.280207e+07,NaN,29990.000000,NaN,NaN,NaN,NaN,2016.000000,8.845400e+04,NaN,NaN,NaN,NaN,2354.000000,NaN,5.000000
75%,1.283131e+07,NaN,45990.000000,NaN,NaN,NaN,NaN,2019.000000,1.488735e+05,NaN,NaN,NaN,NaN,2981.000000,NaN,5.000000
max,1.285246e+07,NaN,999000.000000,NaN,NaN,NaN,NaN,2022.000000,2.700000e+06,NaN,NaN,NaN,NaN,7300.000000,NaN,14.000000

we can use describe method to decribe selected data columns also.

In [47]:
df_new[['Variant','Price', 'Brand'] ].describe()

               Price
count   17048.000000
mean    36777.778038
std     30305.015328
min      1000.000000
25%     18800.000000
50%     29990.000000
75%     45990.000000
max    999000.000000

Df.info is use for get concise summary.

In [41]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17048 entries, 0 to 17047
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                17048 non-null  int64
 1   Name              17048 non-null  object
 2   Price             17048 non-null  int64
 3   Brand             17048 non-null  object
 4   Model             17048 non-null  object
 5   Variant           17048 non-null  object
 6   Series            17048 non-null  object
 7   Year              17048 non-null  int64
 8   Kilometers        17048 non-null  int64
 9   Type              17048 non-null  object
 10  Gearbox           17048 non-null  object
 11  Fuel              17048 non-null  object
 12  Status            17048 non-null  object
 13  CC                17048 non-null  int64
 14  Color             17048 non-null  object
 15  Seating Capacity  17048 non-null  int64
dtypes: int64(6), object(10)
memory usage: 2.1+ MB

Writing a code using DB-API

In [43]:
#from dmodule import connect

# create connection object
#connection = connect('databasename','uername','pswd')

#create a curser object
#cursor = connection.cursor()

# Run queries
#cursor.execute('select * from mytable')
#result_type = cursor.fetchone()
#print(result_type)

#close connection
#connection.close()

Drop data when have null

In [ ]:
# change the data as ? when there is null value
df1=df.replace('?',np.NaN)
# If use df.replace('?',np.nan ,inplace = True) This will make difference in exist data frame not make new data frame

# Drop rows contain null values in a specific column
df=df1.dropna(subset=["price"], axis=0)
# here using axis = 0 to drop entire row which contain null values in specific column
df.head(20)